apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-tlkx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-fmgj-tenant/integ-app-ftkt/hacbs-test-project-tlkx@sha256:0e48c46f9724fdc83e31bd367a580acca4d8377b44bb6930c6d62428ab48be30
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
