apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tlkx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tlkx
    app.kubernetes.io/part-of: integ-app-ftkt
  name: hacbs-test-project-tlkx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tlkx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tlkx
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-fmgj-tenant/integ-app-ftkt/hacbs-test-project-tlkx@sha256:0e48c46f9724fdc83e31bd367a580acca4d8377b44bb6930c6d62428ab48be30
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
